#!/bin/bash

warn() {
  printf "[\033[00;33mWARN\033[0m] $1\n"
}

TARGET=$1
PEM=$2
BRANCH=$3

if [ "$TARGET" = "server1" ]; then
  SSH_OPTION="-i $PEM ubuntu@18.180.157.95"
elif [ "$TARGET" = "server2" ]; then
  SSH_OPTION="-i $PEM ubuntu@35.77.21.99"
elif [ "$TARGET" = "server3" ]; then
  SSH_OPTION="-i $PEM ubuntu@35.74.253.10"
else
  warn "Please set server1 or server2 or server3"
  exit 1
fi

ssh $SSH_OPTION "sudo -u isucon /home/isucon/deploy $BRANCH"
