#!/bin/bash

warn() {
  printf "[\033[00;33mWARN\033[0m] $1\n"
}

TARGET=$1
BRANCH=$2

# branch 指定がなければ current branch を指定したとみなす
if [ -z "$BRANCH" ]; then
  BRANCH=`git rev-parse --abbrev-ref HEAD`
fi

if [ "$TARGET" = "server1" ]; then
  SSH_OPTION="isu11q-1"
elif [ "$TARGET" = "server2" ]; then
  SSH_OPTION="isu11q-2"
elif [ "$TARGET" = "server3" ]; then
  SSH_OPTION="isu11q-3"
else
  warn "Please set server1 or server2 or server3"
  exit 1
fi

echo $SSH_OPTION
echo $BRANCH
# ssh $SSH_OPTION "sudo -u isucon /home/isucon/deploy $BRANCH"
